### ISSUE TITLE
[autopilot] Fix Python 3.10+ import crash from removed collections.Iterable

### ISSUE THREAD

**Issue by wdm0006** [wdm0006/DummyRDD#36]
## Problem
The package fails to import at all on Python 3.10+ (current interpreters; tested on 3.13).

`dummy_spark/resultsiterable.py:25` subclasses the abstract base class via the legacy alias:

```python
import collections
class ResultIterable(collections.Iterable):
```

`collections.Iterable` was deprecated in 3.3 and **removed in 3.10**. Because `dummy_spark/__init__.py` → `context.py` → `rdd.py` imports `ResultIterable`, the whole library raises on import:

```
AttributeError: module 'collections' has no attribute 'Iterable'
```

Repro:
```
$ python3 --version
Python 3.13.6
$ python3 -c "from dummy_spark import SparkContext"
...
  File ".../dummy_spark/resultsiterable.py", line 25, in <module>
    class ResultIterable(collections.Iterable):
AttributeError: module 'collections' has no attribute 'Iterable'
```

This makes DummyRDD completely unusable on any modern Python.

## Proposed change
Use the `collections.abc` location for the ABC (works on Python 3.3+):

```python
import collections.abc
class ResultIterable(collections.abc.Iterable):
```

Scope to `dummy_spark/resultsiterable.py` only. (Optionally note in passing that `.travis.yml` only tests up to 3.5, but the CI modernization is out of scope for this PR.)

## Acceptance
- [ ] `python3 -c "from dummy_spark import SparkContext, SparkConf"` succeeds on Python 3.10+.
- [ ] `ResultIterable` still passes `isinstance(ResultIterable([]), collections.abc.Iterable)`.
- [ ] Existing test suite (`tests/unit/`) imports and runs on Python 3.10+.
- [ ] No other use of the removed `collections.Iterable`/`Mapping`/`Sequence` aliases remains.

## Risk
low — one-line ABC relocation; `collections.abc.Iterable` is the documented, long-standing location and behaves identically.
